# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SystemProfileReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemProfileReportRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=80)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sparkle.SystemProfileReport')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('version', models.CharField(blank=True, max_length=10, null=True)),
                ('short_version', models.CharField(blank=True, max_length=50, null=True)),
                ('dsa_signature', models.CharField(blank=True, max_length=80, null=True)),
                ('length', models.CharField(blank=True, max_length=20, null=True)),
                ('release_notes', models.TextField(blank=True, null=True)),
                ('minimum_system_version', models.CharField(blank=True, max_length=10, null=True)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('update', models.FileField(upload_to='')),
                ('active', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sparkle.Application')),
            ],
        ),
    ]
